# fly.toml app configuration file generated for autumn-snow-275 on 2023-09-08T00:18:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-snow-275"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
